version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "test"
    schedule:
      interval: "weekly"

  # Maintain dependencies for pip (requirements.txt)
  - package-ecosystem: "pip"
    directory: "/"
    target-branch: "test"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  # Maintain dependencies for Docker
  - package-ecosystem: "docker"
    directory: "/"
    target-branch: "test"
    schedule:
      interval: "weekly"
